'use client';

import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { Brain, Loader2 } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Checkbox } from '@/components/ui/checkbox';
import { Label } from '@/components/ui/label';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog';
import { Separator } from '@/components/ui/separator';
import { useToast } from '@/components/ui/use-toast';
import {
  RFP_DOCUMENT_TYPES,
  useGenerateRFPDocument,
  useCustomDocumentTypes,
  isSolutionPlanRequiredError,
  isKBCoverageIncompleteError,
} from '@/lib/hooks/use-rfp-documents';
import { useKBCoverage, KBCoverageBadge } from '@/features/kb-coverage';
import { useGetExecutiveBriefByProject } from '@/lib/hooks/use-executive-brief';
import { useCurrentOrganization } from '@/context/organization-context';
import {
  useSolutionPlanGate,
  SolutionPlanGateCallout,
  SolutionPlanNudgeBanner,
  SOLUTION_PLAN_GATE_BLOCKED_LABEL,
} from '@/features/solution-plan';
import PermissionWrapper from '@/components/permission-wrapper';
import { TemplateSelector } from './template-selector';
import type { RequiredOutputDocument } from '@auto-rfp/core';

/** All built-in document types in win-optimized proposal order.
 * NOTE: QUESTIONNAIRE is excluded — it's auto-generated by the answer pipeline, not manually created. */
const STANDARD_TYPES: { key: string; label: string }[] = [
  { key: 'COVER_LETTER',                  label: RFP_DOCUMENT_TYPES.COVER_LETTER },
  { key: 'EXECUTIVE_SUMMARY',             label: RFP_DOCUMENT_TYPES.EXECUTIVE_SUMMARY },
  { key: 'UNDERSTANDING_OF_REQUIREMENTS', label: RFP_DOCUMENT_TYPES.UNDERSTANDING_OF_REQUIREMENTS },
  { key: 'TECHNICAL_PROPOSAL',            label: RFP_DOCUMENT_TYPES.TECHNICAL_PROPOSAL },
  { key: 'PROJECT_PLAN',                  label: RFP_DOCUMENT_TYPES.PROJECT_PLAN },
  { key: 'TEAM_QUALIFICATIONS',           label: RFP_DOCUMENT_TYPES.TEAM_QUALIFICATIONS },
  { key: 'PAST_PERFORMANCE',              label: RFP_DOCUMENT_TYPES.PAST_PERFORMANCE },
  { key: 'COST_PROPOSAL',                 label: RFP_DOCUMENT_TYPES.COST_PROPOSAL },
  { key: 'MANAGEMENT_APPROACH',           label: RFP_DOCUMENT_TYPES.MANAGEMENT_APPROACH },
  { key: 'RISK_MANAGEMENT',               label: RFP_DOCUMENT_TYPES.RISK_MANAGEMENT },
  { key: 'COMPLIANCE_MATRIX',             label: RFP_DOCUMENT_TYPES.COMPLIANCE_MATRIX },
  { key: 'CERTIFICATIONS',                label: RFP_DOCUMENT_TYPES.CERTIFICATIONS },
  { key: 'APPENDICES',                    label: RFP_DOCUMENT_TYPES.APPENDICES },
  { key: 'MANAGEMENT_PROPOSAL',           label: RFP_DOCUMENT_TYPES.MANAGEMENT_PROPOSAL },
  { key: 'PRICE_VOLUME',                  label: RFP_DOCUMENT_TYPES.PRICE_VOLUME },
  { key: 'QUALITY_MANAGEMENT',            label: RFP_DOCUMENT_TYPES.QUALITY_MANAGEMENT },
  { key: 'CLARIFYING_QUESTIONS',          label: RFP_DOCUMENT_TYPES.CLARIFYING_QUESTIONS },
  { key: 'QUESTIONS_AND_ANSWERS',         label: RFP_DOCUMENT_TYPES.QUESTIONS_AND_ANSWERS },
];

interface DocRow {
  key: string;
  label: string;
  isRequired: boolean;
  isCustom: boolean;
  description?: string | null;
  pageLimit?: string | null;
}

interface DocSelection {
  checked: boolean;
  templateId: string;
}

interface GenerateDocumentDialogProps {
  projectId: string;
  opportunityId: string;
  orgId: string;
  /** Required documents from executive brief (already generated ones should be filtered out by the caller) */
  requiredDocs?: RequiredOutputDocument[];
  onSuccess?: () => void;
}

export const GenerateDocumentDialog = ({
  projectId,
  opportunityId,
  orgId,
  requiredDocs = [],
  onSuccess,
}: GenerateDocumentDialogProps) => {
  const [open, setOpen] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const { trigger: generateDocument } = useGenerateRFPDocument(orgId);
  const { currentOrganization } = useCurrentOrganization();
  const { customTypes } = useCustomDocumentTypes(currentOrganization?.id ?? null);
  const { trigger: fetchBrief, data: briefData } = useGetExecutiveBriefByProject(orgId);
  const { toast } = useToast();

  // Solution Plan gate (T12): gated doc types require a READY plan; exempt
  // types (Q&A-style) stay generatable. Server enforces the same rule (T9).
  const { isGateActive, isGrandfathered, isDocumentTypeBlocked: isPlanBlocked } =
    useSolutionPlanGate(orgId, projectId, opportunityId);

  // KB coverage precheck: name what the KB is missing for a document type
  // *before* generation is triggered. Warns by default; blocks only when the
  // org's gate is armed, matching the server.
  //
  // Gated on `open`: the badge only renders inside the dialog, and the probe's
  // server side pages the org's whole content-library partition. This component
  // mounts with the documents card on every opportunity view — including for
  // users who lack `proposal:create` and will never open it — so fetching on
  // mount would buy nothing and cost a scan per page view.
  const {
    hasRequirements: hasKBRequirements,
    getMissing: getKBMissing,
    isGateEnabled: isKBGateEnabled,
    isDocumentTypeBlocked: isKBBlocked,
    hasVerdict: hasKBVerdict,
  } = useKBCoverage(open ? orgId : undefined);

  /** Either precondition can block a row; both refuse with a 409 server-side. */
  const isDocumentTypeBlocked = useCallback(
    (documentType: string) => isPlanBlocked(documentType) || isKBBlocked(documentType),
    [isPlanBlocked, isKBBlocked],
  );

  // Fetch required docs from brief when dialog opens (if not provided via props)
  useEffect(() => {
    if (open && requiredDocs.length === 0 && projectId && opportunityId) {
      fetchBrief({ projectId, opportunityId }).catch(() => {});
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open]);

  // Merge prop-provided required docs with brief-fetched ones
  const resolvedRequiredDocs: RequiredOutputDocument[] = useMemo(() => {
    if (requiredDocs.length > 0) return requiredDocs;
    const sections = (briefData?.brief as Record<string, unknown> | undefined)?.sections as Record<string, unknown> | undefined;
    const reqSection = sections?.requirements as Record<string, unknown> | undefined;
    const reqData = reqSection?.data as Record<string, unknown> | undefined;
    const compliance = reqData?.submissionCompliance as Record<string, unknown> | undefined;
    return (compliance?.requiredDocuments ?? []) as RequiredOutputDocument[];
  }, [requiredDocs, briefData]);

  // Build the full list of document types
  const requiredKeys = useMemo(
    () => new Set(resolvedRequiredDocs.map((d) => d.documentType)),
    [resolvedRequiredDocs],
  );

  const allRows: DocRow[] = useMemo(() => {
    const requiredDescriptions = new Map(
      resolvedRequiredDocs.map((d) => [d.documentType, { description: d.description, pageLimit: d.pageLimit }]),
    );

    const rows: DocRow[] = STANDARD_TYPES.map((t) => ({
      key: t.key,
      label: t.label,
      isRequired: requiredKeys.has(t.key),
      isCustom: false,
      description: requiredDescriptions.get(t.key)?.description,
      pageLimit: requiredDescriptions.get(t.key)?.pageLimit,
    }));

    // Add custom types
    // EXCLUDE QUESTIONNAIRE - it's auto-generated by the answer pipeline
    for (const ct of customTypes) {
      if (ct.slug === 'QUESTIONNAIRE') continue; // Skip auto-generated types
      if (!rows.some((r) => r.key === ct.slug)) {
        rows.push({
          key: ct.slug,
          label: ct.name,
          isRequired: requiredKeys.has(ct.slug),
          isCustom: true,
          description: ct.description,
        });
      }
    }

    // Add required docs that aren't in standard or custom (edge case)
    // EXCLUDE QUESTIONNAIRE - it's auto-generated by the answer pipeline, not manually created
    for (const rd of resolvedRequiredDocs) {
      if (rd.documentType === 'QUESTIONNAIRE') continue; // Skip auto-generated types
      if (!rows.some((r) => r.key === rd.documentType)) {
        rows.push({
          key: rd.documentType,
          label: rd.name ?? rd.documentType,
          isRequired: true,
          isCustom: false,
          description: rd.description,
          pageLimit: rd.pageLimit,
        });
      }
    }

    return rows;
  }, [resolvedRequiredDocs, requiredKeys, customTypes]);

  // Selections state
  const buildDefaults = useCallback(() => {
    const map = new Map<string, DocSelection>();
    for (const row of allRows) {
      map.set(row.key, {
        checked: row.isRequired && !isDocumentTypeBlocked(row.key),
        templateId: '',
      });
    }
    return map;
  }, [allRows, isDocumentTypeBlocked]);

  const [selections, setSelections] = useState<Map<string, DocSelection>>(buildDefaults);

  // Reset when dialog opens
  const prevOpenRef = React.useRef(false);
  useEffect(() => {
    if (open && !prevOpenRef.current) {
      setSelections(buildDefaults());
    }
    prevOpenRef.current = open;
  }, [open, buildDefaults]);

  // A row is effectively checked only while its type isn't gate-blocked —
  // covers the gate resolving asynchronously after selections were built.
  const isRowChecked = useCallback(
    (key: string) => (selections.get(key)?.checked ?? false) && !isDocumentTypeBlocked(key),
    [selections, isDocumentTypeBlocked],
  );

  const checkedCount = useMemo(
    () => allRows.filter((row) => isRowChecked(row.key)).length,
    [allRows, isRowChecked],
  );

  const updateSelection = (key: string, updates: Partial<DocSelection>) => {
    setSelections((prev) => {
      const next = new Map(prev);
      const current = next.get(key);
      if (current) {
        next.set(key, { ...current, ...updates });
      }
      return next;
    });
  };

  const setAllChecked = (checked: boolean) => {
    setSelections((prev) => {
      const next = new Map(prev);
      for (const [key, val] of next) {
        next.set(key, { ...val, checked: checked && !isDocumentTypeBlocked(key) });
      }
      return next;
    });
  };

  const selectRequired = () => {
    setSelections((prev) => {
      const next = new Map(prev);
      for (const [key, val] of next) {
        next.set(key, { ...val, checked: requiredKeys.has(key) && !isDocumentTypeBlocked(key) });
      }
      return next;
    });
  };

  const handleGenerate = async () => {
    const toGenerate = allRows.filter((r) => isRowChecked(r.key));
    if (toGenerate.length === 0) return;

    setIsGenerating(true);
    try {
      await Promise.all(
        toGenerate.map((row) => {
          const sel = selections.get(row.key);
          return generateDocument({
            projectId,
            opportunityId,
            documentType: row.key,
            ...(sel?.templateId ? { templateId: sel.templateId } : {}),
          });
        }),
      );
      toast({
        title: 'Generation started',
        description: `${toGenerate.length} document${toGenerate.length === 1 ? '' : 's'} queued for generation.`,
      });
      onSuccess?.();
      setOpen(false);
    } catch (err) {
      toast({
        title: isKBCoverageIncompleteError(err)
          ? 'Knowledge base incomplete'
          : isSolutionPlanRequiredError(err)
            ? 'Solution Plan required'
            : 'Generation failed',
        // The refusal message already names the missing categories.
        description: err instanceof Error ? err.message : 'Failed to start generation',
        variant: 'destructive',
      });
    } finally {
      setIsGenerating(false);
    }
  };

  const hasRequired = requiredKeys.size > 0;
  const selectableCount = useMemo(
    () => allRows.filter((row) => !isDocumentTypeBlocked(row.key)).length,
    [allRows, isDocumentTypeBlocked],
  );
  const allChecked = selectableCount > 0 && checkedCount === selectableCount;

  return (
    <PermissionWrapper requiredPermission="proposal:create">
      <Dialog open={open} onOpenChange={setOpen}>
        <DialogTrigger asChild>
          <Button size="sm" variant="outline">
            <Brain className="h-4 w-4 mr-2" />
            Generate
          </Button>
        </DialogTrigger>
        <DialogContent className="sm:max-w-2xl">
          <DialogHeader>
            <DialogTitle>Generate Documents</DialogTitle>
            <DialogDescription>
              Select document types to generate and choose a template for each.
            </DialogDescription>
          </DialogHeader>

          {/* Solution Plan gate callout (T12) */}
          {isGateActive && (
            <SolutionPlanGateCallout
              orgId={orgId}
              projectId={projectId}
              opportunityId={opportunityId}
              onNavigate={() => setOpen(false)}
            />
          )}
          {/* Grandfathered opportunities generate without a plan, but get the ADR-10 nudge */}
          {isGrandfathered && (
            <SolutionPlanNudgeBanner
              orgId={orgId}
              projectId={projectId}
              opportunityId={opportunityId}
              onNavigate={() => setOpen(false)}
            />
          )}

          {/* Quick filters */}
          <div className="flex items-center gap-2">
            <Button
              size="sm"
              variant={allChecked ? 'default' : 'outline'}
              className="h-7 text-xs"
              onClick={() => setAllChecked(!allChecked)}
            >
              {allChecked ? 'Deselect all' : 'Select all'}
            </Button>
            {hasRequired && (
              <Button
                size="sm"
                variant="outline"
                className="h-7 text-xs"
                onClick={selectRequired}
              >
                Select required ({requiredKeys.size})
              </Button>
            )}
            <span className="ml-auto text-xs text-muted-foreground">
              {checkedCount} selected
            </span>
          </div>

          <Separator />

          {/* Document rows */}
          <div className="space-y-1 max-h-96 overflow-y-auto pr-1">
            {allRows.map((row) => {
              const sel = selections.get(row.key);
              const isBlocked = isDocumentTypeBlocked(row.key);
              const isChecked = isRowChecked(row.key);

              return (
                <div
                  key={row.key}
                  className="rounded-lg border px-3 py-2 flex items-center gap-3"
                >
                  <Checkbox
                    checked={isChecked}
                    disabled={isBlocked}
                    onCheckedChange={(checked) =>
                      updateSelection(row.key, { checked: !!checked })
                    }
                    id={`gen-${row.key}`}
                  />
                  <Label
                    htmlFor={`gen-${row.key}`}
                    className={`text-sm font-medium flex-1 min-w-0 truncate ${
                      isBlocked ? 'cursor-not-allowed text-muted-foreground' : 'cursor-pointer'
                    }`}
                  >
                    {row.label}
                  </Label>
                  {isPlanBlocked(row.key) && (
                    <Badge variant="outline" className="text-[10px] px-1.5 py-0 shrink-0 text-muted-foreground">
                      Requires Solution Plan
                    </Badge>
                  )}
                  {/* Only types with KB requirements get a coverage badge —
                      a green tick on the other 16 would carry no information.
                      Withheld until the probe answers: an empty `missing` list
                      reads as "KB ready", which would be a false reassurance
                      while loading and a permanent one if the probe failed. */}
                  {hasKBRequirements(row.key) && hasKBVerdict && (
                    <KBCoverageBadge
                      missing={getKBMissing(row.key)}
                      isBlocking={isKBGateEnabled}
                    />
                  )}
                  {row.isRequired && (
                    <Badge variant="secondary" className="text-[10px] px-1.5 py-0 shrink-0">
                      Required
                    </Badge>
                  )}
                  {row.isCustom && (
                    <Badge variant="outline" className="text-[10px] px-1.5 py-0 shrink-0">
                      Custom
                    </Badge>
                  )}
                  {row.pageLimit && (
                    <span className="text-[10px] text-muted-foreground shrink-0">
                      {row.pageLimit}
                    </span>
                  )}
                  <div className="w-44 shrink-0">
                    <TemplateSelector
                      orgId={orgId}
                      documentType={row.key}
                      value={sel?.templateId ?? ''}
                      onChange={(templateId) =>
                        updateSelection(row.key, { templateId })
                      }
                      disabled={!isChecked}
                    />
                  </div>
                </div>
              );
            })}
          </div>

          <DialogFooter>
            <Button variant="outline" onClick={() => setOpen(false)} disabled={isGenerating}>
              Cancel
            </Button>
            <Button onClick={handleGenerate} disabled={isGenerating || checkedCount === 0}>
              {isGenerating ? (
                <>
                  <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                  Generating…
                </>
              ) : (
                <>
                  <Brain className="h-4 w-4 mr-2" />
                  Generate ({checkedCount})
                </>
              )}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </PermissionWrapper>
  );
};
