export { TemplateFurniturePanel } from './components/TemplateFurniturePanel';
export { FurnitureEditor } from './components/FurnitureEditor';
export { FurniturePreview } from './components/FurniturePreview';
export { PageFurnitureOverlay } from './components/PageFurnitureOverlay';
export { FurnitureSectionToggles } from './components/FurnitureSectionToggles';
export { useTemplateFurniture } from './hooks/useTemplateFurniture';
export type { UseTemplateFurnitureResult } from './hooks/useTemplateFurniture';
export { deriveFurnitureSections, countFurnitureSections } from './lib/sections';
export type { FurnitureSection } from './lib/sections';
export { useResolvedFurnitureImages } from './hooks/useResolvedFurnitureImages';
export { renderFurnitureBandHtml, collectS3Keys } from './lib/render-band';
