import * as cdk from 'aws-cdk-lib';
import { Construct } from 'constructs';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import * as lambdaNodejs from 'aws-cdk-lib/aws-lambda-nodejs';
import * as scheduler from 'aws-cdk-lib/aws-scheduler';
import * as schedulerTargets from 'aws-cdk-lib/aws-scheduler-targets';
import * as iam from 'aws-cdk-lib/aws-iam';
import * as logs from 'aws-cdk-lib/aws-logs';
import * as path from 'path';
import { NagSuppressions } from 'cdk-nag';

export interface RfpDigestStackProps extends cdk.StackProps {
  stage: string;
  commonEnv: Record<string, string>;
  /** Org whose Linear key and Slack webhook the digest reads from Secrets Manager. */
  digestOrgId: string;
  linearProjectId: string;
}

/**
 * Posts the RFP pipeline digest to Slack every Monday at 11am PT and Thursday at
 * 12pm PT. Reads Linear and writes to Slack only — it touches no customer data
 * and needs no DynamoDB access.
 */
export class RfpDigestStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props: RfpDigestStackProps) {
    super(scope, id, props);

    const { stage, commonEnv, digestOrgId, linearProjectId } = props;
    const functionName = `auto-rfp-post-rfp-digest-${stage}`;

    const lambdaRole = new iam.Role(this, 'RfpDigestLambdaRole', {
      assumedBy: new iam.ServicePrincipal('lambda.amazonaws.com'),
    });

    lambdaRole.addToPolicy(
      new iam.PolicyStatement({
        actions: ['logs:CreateLogGroup', 'logs:CreateLogStream', 'logs:PutLogEvents'],
        resources: [
          `arn:aws:logs:${cdk.Aws.REGION}:${cdk.Aws.ACCOUNT_ID}:log-group:/aws/lambda/${functionName}:*`,
        ],
      }),
    );

    lambdaRole.addToPolicy(
      new iam.PolicyStatement({
        actions: ['secretsmanager:GetSecretValue'],
        resources: [
          `arn:aws:secretsmanager:${cdk.Aws.REGION}:${cdk.Aws.ACCOUNT_ID}:secret:linear-api-key-${digestOrgId}-*`,
          `arn:aws:secretsmanager:${cdk.Aws.REGION}:${cdk.Aws.ACCOUNT_ID}:secret:slack-webhook-api-key-${digestOrgId}-*`,
        ],
      }),
    );

    const logGroup = new logs.LogGroup(this, 'PostRfpDigestLogGroup', {
      logGroupName: `/aws/lambda/${functionName}`,
      retention: stage === 'prod' ? logs.RetentionDays.INFINITE : logs.RetentionDays.TWO_WEEKS,
      removalPolicy: cdk.RemovalPolicy.DESTROY,
    });

    const postRfpDigestLambda = new lambdaNodejs.NodejsFunction(this, 'PostRfpDigestFn', {
      functionName,
      entry: path.join(__dirname, '../../apps/functions/src/handlers/rfp-digest/post-rfp-digest.ts'),
      handler: 'handler',
      runtime: lambda.Runtime.NODEJS_22_X,
      timeout: cdk.Duration.minutes(2),
      memorySize: 512,
      role: lambdaRole,
      environment: {
        ...commonEnv,
        RFP_DIGEST_ORG_ID: digestOrgId,
        RFP_DIGEST_PROJECT_ID: linearProjectId,
      },
      bundling: {
        minify: true,
        sourceMap: true,
        externalModules: ['@aws-sdk/*', '@smithy/*'],
      },
    });

    postRfpDigestLambda.node.addDependency(logGroup);

    // EventBridge Scheduler (not events.Rule) because it honours a timezone —
    // the wall-clock times stay fixed across DST changes. Monday and Thursday run
    // at different hours, so they need separate schedules sharing the same target.
    const digestTarget = new schedulerTargets.LambdaInvoke(postRfpDigestLambda, { retryAttempts: 2 });

    new scheduler.Schedule(this, 'RfpDigestScheduleMon', {
      scheduleName: `auto-rfp-rfp-digest-mon-${stage}`,
      description: 'Posts the RFP pipeline digest to Slack Monday at 11am PT',
      schedule: scheduler.ScheduleExpression.cron({
        minute: '0',
        hour: '11',
        weekDay: 'MON',
        month: '*',
        year: '*',
        timeZone: cdk.TimeZone.AMERICA_LOS_ANGELES,
      }),
      target: digestTarget,
    });

    new scheduler.Schedule(this, 'RfpDigestScheduleThu', {
      scheduleName: `auto-rfp-rfp-digest-thu-${stage}`,
      description: 'Posts the RFP pipeline digest to Slack Thursday at 12pm PT',
      schedule: scheduler.ScheduleExpression.cron({
        minute: '0',
        hour: '12',
        weekDay: 'THU',
        month: '*',
        year: '*',
        timeZone: cdk.TimeZone.AMERICA_LOS_ANGELES,
      }),
      target: digestTarget,
    });

    // The scheduler's invoke role is generated by CDK, so it can only be reached
    // by stack-level suppression rather than a resource reference.
    NagSuppressions.addStackSuppressions(
      this,
      [
        {
          id: 'AwsSolutions-IAM5',
          reason:
            'EventBridge Scheduler needs lambda:InvokeFunction on the function alias wildcard to invoke a specific version.',
          appliesTo: ['Resource::<PostRfpDigestFnC1D5E7BF.Arn>:*'],
        },
      ],
      true,
    );

    NagSuppressions.addResourceSuppressions(
      lambdaRole,
      [
        {
          id: 'AwsSolutions-IAM5',
          reason:
            'Log streams and secret versions carry generated suffixes, so the ARNs are only addressable with a trailing wildcard. Both are already scoped to this function and this org.',
          appliesTo: [
            `Resource::arn:aws:logs:<AWS::Region>:<AWS::AccountId>:log-group:/aws/lambda/${functionName}:*`,
            `Resource::arn:aws:secretsmanager:<AWS::Region>:<AWS::AccountId>:secret:linear-api-key-${digestOrgId}-*`,
            `Resource::arn:aws:secretsmanager:<AWS::Region>:<AWS::AccountId>:secret:slack-webhook-api-key-${digestOrgId}-*`,
          ],
        },
      ],
      true,
    );

    NagSuppressions.addResourceSuppressions(
      postRfpDigestLambda,
      [
        {
          id: 'AwsSolutions-L1',
          reason: 'Node.js 22 is the newest runtime cdk-nag recognises here; it is current LTS.',
        },
      ],
      true,
    );

    new cdk.CfnOutput(this, 'PostRfpDigestLambdaArn', {
      value: postRfpDigestLambda.functionArn,
      description: 'Lambda ARN for the RFP pipeline digest',
    });
  }
}
