/**
 * csv.ts
 *
 * Shared CSV cell serialization for the RFP-tracking exports. Centralized so the
 * pipeline export (export-csv.ts) and the per-table metrics exports
 * (export-metrics-csv.ts) share one hardened implementation.
 */

/**
 * Characters that trigger formula evaluation when a CSV is opened in Excel /
 * Google Sheets / LibreOffice. A cell whose first non-whitespace character is
 * any of these is treated as a formula, so an attacker-controlled value like
 * `=HYPERLINK(...)`, `  =cmd|...` (leading spaces), or `\n=cmd` (leading
 * newline) would execute. We match after any leading whitespace so a trigger
 * hidden behind spaces/tabs/newlines is still caught. RFP titles, owner names,
 * and source labels are Linear-synced free text, so they are untrusted.
 */
const FORMULA_TRIGGER = /^\s*[=+\-@]/;

/**
 * Escape a CSV cell:
 * 1. Neutralize formula injection — prefix a single quote to the ORIGINAL value
 *    of any STRING whose first non-whitespace character is a formula-trigger
 *    character so spreadsheet apps treat it as text, not a formula. Numbers are
 *    generated by our own code (never user input), so a legitimate negative
 *    like `-5` is left as a real number rather than coerced to text.
 * 2. Wrap in double quotes and double any embedded double quotes (RFC 4180).
 */
export const csvCell = (value: string | number | null | undefined): string => {
  if (value === null || value === undefined) return '""';
  const raw = String(value);
  const safe = typeof value === 'string' && FORMULA_TRIGGER.test(raw) ? `'${raw}` : raw;
  return `"${safe.replace(/"/g, '""')}"`;
};

/**
 * Slugify an org name into a filename segment: lowercase, collapse runs of
 * non-alphanumeric characters to single dashes, strip leading/trailing dashes,
 * and fall back to `export` when the result is empty (e.g. `---`).
 */
export const slug = (orgName: string): string =>
  orgName
    .replace(/[^a-z0-9]+/gi, '-')
    .toLowerCase()
    .replace(/^-+|-+$/g, '') || 'export';
