/**
 * csv.ts
 *
 * Shared CSV cell serialization for the RFP-tracking exports. Centralized so the
 * pipeline export (export-csv.ts) and the per-table metrics exports
 * (export-metrics-csv.ts) share one hardened implementation.
 */

/**
 * Characters that trigger formula evaluation when a CSV is opened in Excel /
 * Google Sheets / LibreOffice. A cell beginning with any of these is treated as
 * a formula, so an attacker-controlled value like `=HYPERLINK(...)` or
 * `=cmd|...` would execute. RFP titles, owner names, and source labels are
 * Linear-synced free text, so they are untrusted.
 */
const FORMULA_TRIGGER = /^[=+\-@\t\r]/;

/**
 * Escape a CSV cell:
 * 1. Neutralize formula injection — prefix a single quote to any STRING value
 *    that begins with a formula-trigger character so spreadsheet apps treat it
 *    as text, not a formula. Numbers are generated by our own code (never user
 *    input), so a legitimate negative like `-5` is left as a real number rather
 *    than coerced to text.
 * 2. Wrap in double quotes and double any embedded double quotes (RFC 4180).
 */
export const csvCell = (value: string | number | null | undefined): string => {
  if (value === null || value === undefined) return '""';
  const raw = String(value);
  const safe = typeof value === 'string' && FORMULA_TRIGGER.test(raw) ? `'${raw}` : raw;
  return `"${safe.replace(/"/g, '""')}"`;
};
